# Generated by Django 3.0.8 on 2020-10-25 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20201025_0100'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'item')},
        ),
    ]
