# Generated by Django 3.0.8 on 2020-10-19 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='course',
            name='course_room',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='course_teacher',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='Assignemnt_assigned',
            field=models.DateField(default=datetime.datetime(2020, 10, 18, 23, 31, 50, 995125)),
        ),
    ]
