# Generated by Django 3.0.8 on 2020-10-19 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20201018_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_enrolled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='Assignemnt_assigned',
            field=models.DateField(default=datetime.datetime(2020, 10, 19, 19, 49, 39, 739221)),
        ),
    ]
