# Generated by Django 3.0.8 on 2020-10-20 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20201019_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='Assignment_type',
        ),
        migrations.AddField(
            model_name='assignments',
            name='Assignement_type',
            field=models.CharField(default='Homework', max_length=15),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='Assignemnt_assigned',
            field=models.DateField(default=datetime.datetime(2020, 10, 19, 20, 10, 57, 536441)),
        ),
    ]
