# Generated by Django 3.0.8 on 2020-10-20 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20201019_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignments',
            old_name='Assignement_type',
            new_name='Assignment_type',
        ),
        migrations.AlterField(
            model_name='assignments',
            name='Assignemnt_assigned',
            field=models.DateField(default=datetime.datetime(2020, 10, 19, 20, 12, 23, 563352)),
        ),
    ]
